src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Room::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $room_id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $checkin_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $checkout_date;

    /**
     * @ORM\OneToOne(targetEntity=Payment::class, cascade={"persist", "remove"})
     */
    private $payment_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $payment_method;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRoomId(): ?Room
    {
        return $this->room_id;
    }

    public function setRoomId(?Room $room_id): self
    {
        $this->room_id = $room_id;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCheckinDate(): ?\DateTimeInterface
    {
        return $this->checkin_date;
    }

    public function setCheckinDate(\DateTimeInterface $checkin_date): self
    {
        $this->checkin_date = $checkin_date;

        return $this;
    }

    public function getCheckoutDate(): ?\DateTimeInterface
    {
        return $this->checkout_date;
    }

    public function setCheckoutDate(\DateTimeInterface $checkout_date): self
    {
        $this->checkout_date = $checkout_date;

        return $this;
    }

    public function getPaymentId(): ?payment
    {
        return $this->payment_id;
    }

    public function setPaymentId(?payment $payment_id): self
    {
        $this->payment_id = $payment_id;

        return $this;
    }

    public function getPaymentMethod(): ?string
    {
        return $this->payment_method;
    }

    public function setPaymentMethod(string $payment_method): self
    {
        $this->payment_method = $payment_method;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Doctrine\DBAL\Types\DateType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('checkin_date')
            ->add('checkout_date')
            ->add('payment_method')
            ->add('room_id')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Entity\Room;
use App\Form\ReservationType;
use App\Repository\KindRepository;
use App\Repository\ReservationRepository;
use App\Repository\RoomRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository, UserRepository $userRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
            $user = $userRepository->find($this->getUser()),
            'user_reservations' => $reservationRepository->find($user)
        ]);
    }

    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request, RoomRepository $roomRepository): Response
    {
        $reservation = new Reservation();
        $roomId = $request->query->get('id');
        if (!empty($roomId) && is_numeric($roomId)) {
            $reservation->setRoomId($roomRepository->find($roomId));
        }
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservation->setUserId($this->getUser());

            $amount = $form['room_id']->getData();
            $begin = $form['checkin_date']->getData();
            $end = $form['checkout_date']->getData();


            $kind = $roomRepository->find($amount);


            $i = 0;

            foreach ($kind->getReservations() as $res) {
                if (($begin >= $res->getCheckinDate() && $begin <= $res->getCheckoutDate()) || ($end >= $res->getCheckinDate() && $end <= $res->getCheckoutDate()) || ($begin <= $res->getCheckinDate() && $end >= $res->getCheckoutDate())) {
                    $i++;
                    $this->addFlash('error',  'This date has already been reserved. This room will be available at'." ".$res->getCheckoutDate()->format('d-m-Y'));
                }

            }
            if ($i == 0) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($reservation);
                $entityManager->flush();

                return $this->redirectToRoute('reservation_index');
            }
        }


        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
    <h1>Reservation index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Checkin_date</th>
            <th>Checkout_date</th>
            <th>Payment_method</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% if is_granted('ROLE_ADMIN') %}
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.checkinDate ? reservation.checkinDate|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ reservation.checkoutDate ? reservation.checkoutDate|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ reservation.paymentMethod }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}">show</a>
                        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>
                    </td>
                </tr>

            {% endfor %}
        {% elseif is_granted('ROLE_ADMIN') == false %}
            {% for reservation in user_reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.checkinDate ? reservation.checkinDate|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ reservation.checkoutDate ? reservation.checkoutDate|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ reservation.paymentMethod }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}">show</a>
                        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>
                    </td>
                </tr>

            {% endfor %}

        {% endif %}

        </tbody>
    </table>

    <a href="{{ path('reservation_new') }}">Create new</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    {% for flashMessage in app.flashes('error') %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Error</h4>
            <p>{{ flashMessage }}</p>
        </div>
    {% endfor %}

    <a href="{{ path('reservation_index') }}">back to list</a>

{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Checkin_date</th>
                <td>{{ reservation.checkinDate ? reservation.checkinDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Checkout_date</th>
                <td>{{ reservation.checkoutDate ? reservation.checkoutDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Payment_method</th>
                <td>{{ reservation.paymentMethod }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">back to list</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}