src/Entity/Kind.php
<?php

namespace App\Entity;

use App\Repository\KindRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=KindRepository::class)
 */
class Kind
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $additional_price;

    /**
     * @ORM\OneToMany(targetEntity=Kind::class, mappedBy="kind")
     */
    private $rooms;

    public function __construct()
    {
        $this->rooms = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdditionalPrice(): ?float
    {
        return $this->additional_price;
    }

    public function setAdditionalPrice(float $additional_price): self
    {
        $this->additional_price = $additional_price;

        return $this;
    }

    /**
     * @return Collection|Room[]
     */
    public function getRooms(): Collection
    {
        return $this->rooms;
    }

    public function addRoom(Room $room): self
    {
        if (!$this->rooms->contains($room)) {
            $this->rooms[] = $room;
            $room->setKindId($this);
        }

        return $this;
    }

    public function removeRoom(Room $room): self
    {
        if ($this->rooms->contains($room)) {
            $this->rooms->removeElement($room);
            // set the owning side to null (unless already changed)
            if ($room->getKindId() === $this) {
                $room->setKindId(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->description;
    }
}

src/Form/KindType.php
<?php

namespace App\Form;

use App\Entity\Kind;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class KindType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('additional_price')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Kind::class,
        ]);
    }
}

src/Controller/KindController.php
<?php

namespace App\Controller;

use App\Entity\Kind;
use App\Form\KindType;
use App\Repository\KindRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/kind")
 */
class KindController extends AbstractController
{
    /**
     * @Route("/", name="kind_index", methods={"GET"})
     */
    public function index(KindRepository $kindRepository): Response
    {
        return $this->render('kind/index.html.twig', [
            'kinds' => $kindRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="kind_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $kind = new Kind();
        $form = $this->createForm(KindType::class, $kind);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($kind);
            $entityManager->flush();

            return $this->redirectToRoute('kind_index');
        }

        return $this->render('kind/new.html.twig', [
            'kind' => $kind,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="kind_show", methods={"GET"})
     */
    public function show(Kind $kind): Response
    {
        return $this->render('kind/show.html.twig', [
            'kind' => $kind,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="kind_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Kind $kind): Response
    {
        $form = $this->createForm(KindType::class, $kind);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('kind_index');
        }

        return $this->render('kind/edit.html.twig', [
            'kind' => $kind,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="kind_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Kind $kind): Response
    {
        if ($this->isCsrfTokenValid('delete'.$kind->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($kind);
            $entityManager->flush();
        }

        return $this->redirectToRoute('kind_index');
    }
}

templates/kind/_delete_form.html.twig
<form method="post" action="{{ path('kind_delete', {'id': kind.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ kind.id) }}">
    <button class="btn">Delete</button>
</form>

templates/kind/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/kind/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Kind{% endblock %}

{% block body %}
    <h1>Edit Kind</h1>

    {{ include('kind/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('kind_index') }}">back to list</a>

    {{ include('kind/_delete_form.html.twig') }}
{% endblock %}

templates/kind/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kind index{% endblock %}

{% block body %}
    <h1>Kind index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Additional_price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for kind in kinds %}
            <tr>
                <td>{{ kind.id }}</td>
                <td>{{ kind.description }}</td>
                <td>{{ kind.additionalPrice }}</td>
                <td>
                    <a href="{{ path('kind_show', {'id': kind.id}) }}">show</a>
                    <a href="{{ path('kind_edit', {'id': kind.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('kind_new') }}">Create new</a>
{% endblock %}

templates/kind/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Kind{% endblock %}

{% block body %}
    <h1>Create new Kind</h1>

    {{ include('kind/_form.html.twig') }}

    <a href="{{ path('kind_index') }}">back to list</a>
{% endblock %}

templates/kind/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kind{% endblock %}

{% block body %}
    <h1>Kind</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ kind.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ kind.description }}</td>
            </tr>
            <tr>
                <th>Additional_price</th>
                <td>{{ kind.additionalPrice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('kind_index') }}">back to list</a>

    <a href="{{ path('kind_edit', {'id': kind.id}) }}">edit</a>

    {{ include('kind/_delete_form.html.twig') }}
{% endblock %}