src/Entity/Extra.php
<?php

namespace App\Entity;

use App\Repository\ExtrasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExtrasRepository::class)
 */
class Extra
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $additional_cost;

    /**
     * @ORM\OneToMany(targetEntity=Room::class, mappedBy="extra")
     */
    private $room_id;

    public function __construct()
    {
        $this->room_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdditionalCost(): ?float
    {
        return $this->additional_cost;
    }

    public function setAdditionalCost(float $additional_cost): self
    {
        $this->additional_cost = $additional_cost;

        return $this;
    }

    /**
     * @return Collection|Room[]
     */
    public function getRoomId(): Collection
    {
        return $this->room_id;
    }

    public function addRoomId(Room $roomId): self
    {
        if (!$this->room_id->contains($roomId)) {
            $this->room_id[] = $roomId;
            $roomId->setExtra($this);
        }

        return $this;
    }

    public function removeRoomId(Room $roomId): self
    {
        if ($this->room_id->contains($roomId)) {
            $this->room_id->removeElement($roomId);
            // set the owning side to null (unless already changed)
            if ($roomId->getExtra() === $this) {
                $roomId->setExtra(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->description;
    }

}

src/Form/ExtraType.php
<?php

namespace App\Form;

use App\Entity\Extra;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExtraType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('additional_cost')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Extra::class,
        ]);
    }
}

src/Controller/ExtraController.php
<?php

namespace App\Controller;

use App\Entity\Extra;
use App\Form\ExtraType;
use App\Repository\ExtrasRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/extra")
 */
class ExtraController extends AbstractController
{
    /**
     * @Route("/", name="extra_index", methods={"GET"})
     */
    public function index(ExtrasRepository $extrasRepository): Response
    {
        return $this->render('extra/index.html.twig', [
            'extras' => $extrasRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="extra_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $extra = new Extra();
        $form = $this->createForm(ExtraType::class, $extra);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($extra);
            $entityManager->flush();

            return $this->redirectToRoute('extra_index');
        }

        return $this->render('extra/new.html.twig', [
            'extra' => $extra,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="extra_show", methods={"GET"})
     */
    public function show(Extra $extra): Response
    {
        return $this->render('extra/show.html.twig', [
            'extra' => $extra,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="extra_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Extra $extra): Response
    {
        $form = $this->createForm(ExtraType::class, $extra);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('extra_index');
        }

        return $this->render('extra/edit.html.twig', [
            'extra' => $extra,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="extra_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Extra $extra): Response
    {
        if ($this->isCsrfTokenValid('delete'.$extra->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($extra);
            $entityManager->flush();
        }

        return $this->redirectToRoute('extra_index');
    }
}

templates/extra/_delete_form.html.twig
<form method="post" action="{{ path('extra_delete', {'id': extra.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ extra.id) }}">
    <button class="btn">Delete</button>
</form>

templates/extra/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/extra/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Extra{% endblock %}

{% block body %}
    <h1>Edit Extra</h1>

    {{ include('extra/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('extra_index') }}">back to list</a>

    {{ include('extra/_delete_form.html.twig') }}
{% endblock %}

templates/extra/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Extra index{% endblock %}

{% block body %}
    <h1>Extra index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Additional_cost</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for extra in extras %}
            <tr>
                <td>{{ extra.id }}</td>
                <td>{{ extra.description }}</td>
                <td>{{ extra.additionalCost }}</td>
                <td>
                    <a href="{{ path('extra_show', {'id': extra.id}) }}">show</a>
                    <a href="{{ path('extra_edit', {'id': extra.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('extra_new') }}">Create new</a>
{% endblock %}

templates/extra/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Extra{% endblock %}

{% block body %}
    <h1>Create new Extra</h1>

    {{ include('extra/_form.html.twig') }}

    <a href="{{ path('extra_index') }}">back to list</a>
{% endblock %}

templates/extra/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Extra{% endblock %}

{% block body %}
    <h1>Extra</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ extra.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ extra.description }}</td>
            </tr>
            <tr>
                <th>Additional_cost</th>
                <td>{{ extra.additionalCost }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('extra_index') }}">back to list</a>

    <a href="{{ path('extra_edit', {'id': extra.id}) }}">edit</a>

    {{ include('extra/_delete_form.html.twig') }}
{% endblock %}